### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by phamdannyh** [mapp-digital/Mapp-Intelligence-GTM-Serverside-Tag#1]
When reviewing your template we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

https://github.com/mapp-digital/Mapp-Intelligence-GTM-Serverside-Tag/blob/686947d681e1a8d8776e7805f78e5bca46540e1a/template.tpl#L1306

**Comment by stiegi** [comment]
@phamdannyh Thank you very much for the feedback. I have updated the template and metadata.yaml file, and encodeUri is used for trackDomain and trackId in the trackRequest url now.

**Comment by stiegi** [comment]
@phamdannyh Hi, any news when this will be published on the gallery?
